### ISSUE TITLE
сделай поддержку винды

### ISSUE THREAD

**Issue by xterdd** [z3r0memory/Sayori#1]
я пукнул

**Comment by z3r0memory** [comment]
нет

**Comment by xterdd** [comment]
ну и пошёл в одно место

**Comment by z3r0memory** [comment]
лошара оно кроссплатформенное

**Comment by xterdd** [comment]
я всё равно юзать небуду

**Comment by z3r0memory** [comment]
лох

**Comment by xterdd** [comment]
только ты

**Comment by z3r0memory** [comment]
щас забаню в репо

**Comment by rubinsser** [comment]
блять сука пусть он сам и напишет ебанную прогу для винды
Ну или пусть wsl пользуется

**Comment by z3r0memory** [comment]
петухон и жабаскрипт - кроссплатформенные пока речь не заходит о нативных либах, в моем скрипте только вебсокеты и rich (python), в плагине только вебсокеты

**Comment by YuriTop** [comment]
У меня встал

**Comment by rubinsser** [comment]
Ну впринципе тоже можно, но если ему нужен exe в чём его проблема скомпилить Py файл?

**Comment by z3r0memory** [comment]
> У меня встал

на юри?

**Comment by YuriTop** [comment]
> > У меня встал
> 
> на юри?

На на

**Comment by rubinsser** [comment]
на бравл старс

**Comment by rubinsser** [comment]
блять мы общаемся в гитхабе

**Comment by z3r0memory** [comment]
если бы мне было не лень я бы сделал на плюсах (нативно под линукс), а тут петухон который может хоть где стартовать

**Comment by YuriTop** [comment]
discord v2 чек

**Comment by z3r0memory** [comment]
давайте сделаем каналы тут

**Comment by rubinsser** [comment]
го

**Comment by YuriTop** [comment]
Го

**Comment by YuriTop** [comment]
ти лох

**Comment by rubinsser** [comment]
сам

**Comment by z3r0memory** [comment]
#2
